// <auto-generated />
using AgroClimate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroClimate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240916224330_NewMigrations")]
    partial class NewMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroClimate.Models.Agricultor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("Agricultores");
                });

            modelBuilder.Entity("AgroClimate.Models.AgricultorFazenda", b =>
                {
                    b.Property<int>("AgricultorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FazendaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AgricultorId", "FazendaId");

                    b.HasIndex("FazendaId");

                    b.ToTable("AgricultorFazendas");
                });

            modelBuilder.Entity("AgroClimate.Models.Fazenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("Fazendas");
                });

            modelBuilder.Entity("AgroClimate.Models.AgricultorFazenda", b =>
                {
                    b.HasOne("AgroClimate.Models.Agricultor", "Agricultor")
                        .WithMany("AgricultorFazendas")
                        .HasForeignKey("AgricultorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroClimate.Models.Fazenda", "Fazenda")
                        .WithMany("AgricultorFazendas")
                        .HasForeignKey("FazendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agricultor");

                    b.Navigation("Fazenda");
                });

            modelBuilder.Entity("AgroClimate.Models.Agricultor", b =>
                {
                    b.Navigation("AgricultorFazendas");
                });

            modelBuilder.Entity("AgroClimate.Models.Fazenda", b =>
                {
                    b.Navigation("AgricultorFazendas");
                });
#pragma warning restore 612, 618
        }
    }
}
